# MySQL database connection
connection:
  host: db
  port: 3306
  database: fivem
  user: root
  password: password
  charset: utf8mb4
  logging: false

migrations:
  automatic: true

# How often the server uptime log is updated
boot_history:
  update_frequency: 15 secs # Minimum is 10 seconds
