# Display options
display:
  name: NFive
  game: Custom
  map: Los Santos

# Set logging output level per component
# Levels: Trace|Debug|Info|Warn|Error
log:
  core: Trace
  rpc: Debug
  events: Debug

  plugins:
    # Default log level for plugins unless overriden
    default: Trace

    # Override indervidual plugin log level
    NFive/plugin-example: Error
